### ISSUE TITLE
Support for Central Scene command class

### ISSUE THREAD

**Issue by bluewalk** [genielabs/zwave-lib-dotnet#14]
I was wondering if there is support for COMMAND_CLASS_CENTRAL_SCENE.

I now own a ZRC-90 scene master, but it only uses the Central Scene command class, as it looks now it is not yet supported by this lib...

At the OpenZWave issues I've found the following for implementation: https://github.com/OpenZWave/open-zwave/issues/367#issuecomment-212574919

I am attempting to add the command class myself, when successful I will create a pull request :)

**Comment by ben-voss** [comment]
Please see pull request #21 which add your requested support.  Since I don't own the device I cannot test the implementation.  Would you be able to test this and let me know if there are any problems.

**Comment by bluewalk** [comment]
In fact I've written the central scene support myself as well and created a pull request a couple of weeks ago 😉

**Comment by bluewalk** [comment]
See pull request #15

**Comment by ben-voss** [comment]
Ahh yes so you did.  I viewed that pull request on a mobile device that a bit glitchy and only saw the changes for the logging and the timestamp.  My apologies - we can ignore this pull request.

**Comment by bluewalk** [comment]
My PR has been merged so closing this issue.
