### ISSUE TITLE
Windows serial port format?

### ISSUE THREAD

**Issue by reskin** [genielabs/zwave-lib-dotnet#17]
My Z-stick is assigned COM7 ... I tried "COM7", "com7", "COM7COM", can't get it to work on Windows in C#... am I being dense?  It shows 0 nodes and not connected but if I load it in Axial Server I see my irrigation controller.

**Comment by yesyesuk** [comment]
I got the Test.ZWave demo "working" using this COM port name:

`private static string serialPortName = "COM10";`
(line 16 in Program.cs)

**Comment by Bounz** [comment]
@reskin, this could be possible if you try to run Test program while Axial Server is also running. I have had the similar issue on Raspberry Pi when other application had ownership of z-wave stick.
