### ISSUE TITLE
Irrigation control with ZWaveLib?

### ISSUE THREAD

**Issue by reskin** [genielabs/zwave-lib-dotnet#18]
I had posted a bounty on this... I don't see that this is something supported by the library yet?

https://www.upwork.com/jobs/~01d77bb5ee3733fbac

**Comment by Bounz** [comment]
Looks interesting.
I'm working on covering this lib with unit-tests so I continually use the documentation.
Implementing missing command classes is the next goal after writing unit-tests, but there is no a substantial difference what to make first.
I'll try to implement IRRIGATION command class during this weekend. After that, it would be possible to write the test program you are asking about.

**Comment by genemars** [comment]
added by @Bounz  with pr #19

**Comment by reskin** [comment]
Sweet! The community would benefit but I am also willing to pay to get this
put ahead of other priorities since it is a potential commercial investment.

Jason




*JASON RESKIN* | Software Engineer

jreskin@imodules.com
direct: 913.685.5251
office: 913.888.0772

iModules Software <http://www.imodules.com/>
