### ISSUE TITLE
Error - Raspberry PI

### ISSUE THREAD

**Issue by FrankDoersam** [genielabs/zwave-lib-dotnet#32]
Hello,
Thank you for the project. Something has to be taken into consideration when using the Raspberry PI, the Gen5 stick lights up wildly all the time. After establishing the connection, the connection will break off again. With the Discovery no devices are found, over Windows it runs normally.
Kind regards
Frank Dörsam

**Comment by genemars** [comment]
this should be fixed now by 1.0.20
