### ISSUE TITLE
Motion Sensor notifications

### ISSUE THREAD

**Issue by Jerem-35** [genielabs/zwave-lib-dotnet#36]
Hello,

I am currently facing issues with motions sensors notifications with a Fibaro FGMS-001 (I did try with another motion sensor with the same result). 

How am I supposed to be notified when a motion is detected?  I thought it would work with the "NodeUpdated" callback from ZWaveController but it never raises such event. 

I dit try to use SensorBinary.Get(node) but as a result I am notifiied that the device is in sleeping mode. 

Thank you.

Jérémy

**Comment by Bounz** [comment]
Have you added your controller to the Association Group 3 in sensor settings?

**Comment by Jerem-35** [comment]
Thank you for your quick answer!

I did not! Is it something that has to be configured in zwavenodes.xml ?
I did not find anything about association groups.

**Comment by Bounz** [comment]
No, you configure it in node settings.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/3062744/53513686-f76c6800-3ad6-11e9-9ff2-d166145ba5ea.png">

<img width="547" alt="image" src="https://user-images.githubusercontent.com/3062744/53513735-0f43ec00-3ad7-11e9-8a34-f2d640f3c7b0.png">

You have to add your controller (usually node 1) to this group.

**Comment by Jerem-35** [comment]
If I refer to the code, it is something that can be done with the following function of Association.cs?

public static ZWaveMessage Set(ZWaveNode node, byte groupid, byte targetNodeId)
(In this case with, groupeid=3, targetnodid=1)

From which application your screenshots are taken?

**Comment by Bounz** [comment]
Yes, this code should work.
Screenshots were taken from HomeGenie home automation system https://github.com/genielabs/HomeGenie

**Comment by Jerem-35** [comment]
Thank you a lot for your answers. I did not know anything about these groups, sorry for that.
Here is the code I used for the ones who face the same issue :
 
ZWaveNode node0 = controller.GetNode(14); // My motion sensor
 Association.Set(node0 , 3, 1); 

Now motion notifications are correctly raised.
