### ISSUE TITLE
Secure Include and related configuration

### ISSUE THREAD

**Issue by marcus-j-davies** [genielabs/zwave-lib-dotnet#45]
Hello,

Looking through the source, I see a lot of mention, relating to security, encryption keys and what not.
However, the public methods that are available  under the **ZWaveController** do not reveal any methods to control security.

i.e Starting Secure Include, Setting the encryption key etc etc.

Question.
Does your Lib support Secure include, setting the key, and operating secure devices?

Would appreciate a response.

**Comment by Bounz** [comment]
Hi, Marcus!

Unfortunately zwave-lib doesn't work properly with secure devices at the moment.

**Comment by marcus-j-davies** [comment]
Thank you for the Clarification Alexander.

**Comment by magnuand** [comment]
Does this mean this library won't work with any command classes that require secure mode S0?

**Comment by marcus-j-davies** [comment]
I can’t see any method that allows setting the network key or anything like that. So my guess is no - though the library does have some of the foundations in place.

Hopefully someone from this project can shed some light.

I’m currently studying the ZWave docs my self, as I’m building my own library - kind of a learning exercise.

**Comment by marcus-j-davies** [comment]
no longer using the lib
