### ISSUE TITLE
Possibility to licence the library under LPGL license?

### ISSUE THREAD

**Issue by seeseekey** [genielabs/zwave-lib-dotnet#7]
Hi,

it is possible to license the library unter LGPL license (or another more permissive license like MIT)?

**Comment by genemars** [comment]
I think so. I'll do this in the next release.

**Comment by Redth** [comment]
Any update on this? Some of us would love to build on top of this (and upstream improvements) but it would need to be MIT or Apache 2 for us to use it. 

If you're able to change the license it would be much appreciated!

**Comment by Clancey** [comment]
I agree. I would love to add this as a dependency and work on it. But I also need MIT or Apache 2

**Comment by Redth** [comment]
Awesome, thanks so much! looking forward to creating some cool .net core open source home automation stuff with this!
